### ISSUE TITLE
Different .csv file

### ISSUE THREAD

**Issue by inkinkz** [SarthakV7/AI-based-indian-license-plate-detection#1]
I followed your tutorial until the part involving the .csv file. I downloaded what you provided here and I realize that the data are different. The one provided here has no column named 'Character' and it has only 779 rows, not 1079 like what you showed [here](https://towardsdatascience.com/ai-based-indian-license-plate-detector-de9d48ca8951) in step 7.

**Comment by sanfernoronha** [comment]
Same issue.....Is there a complete csv file?

**Comment by SarthakV7** [comment]
Hi, updated the code, please check now.
