### ISSUE TITLE
Error when checking target: expected dense_2 to have shape (36,) but got array with shape (27,)

### ISSUE THREAD

**Issue by RYucel** [SarthakV7/AI-based-indian-license-plate-detection#2]
`Error when checking target: expected dense_2 to have shape (36,) but got array with shape (27,)`

csv files also not same as in the code (Character column is not there)

**Comment by divyamdr** [comment]
> `Error when checking target: expected dense_2 to have shape (36,) but got array with shape (27,)`
> 
> CSV files also not same as in the code (Character column is not there)

I too get the same error. Did you resolve??

**Comment by SarthakV7** [comment]
I've updated the code, please check the .ipynb file.

**Comment by divyamdr** [comment]
Thank you
