### ISSUE TITLE
csv file is not complete

### ISSUE THREAD

**Issue by Shabana-Tamboli** [SarthakV7/AI-based-indian-license-plate-detection#3]
image_data.csv file is not as expected. pls update the expected file

**Comment by trshimpi** [comment]
Yes , the dimensions are 780 rows × 786 columns ,you have mentioned 1080 rows and also the last column of characters is missing from the dataset . Please update the dataset asap

**Comment by SarthakV7** [comment]
I've updated the dataflow method in the code, removed the .csv file and uploaded the compressed data.zip file that contains train and test data ready for keras.datageneration class.
Please check the .ipynb file.
